cli/command/container: fix redefinition of the built-in function close (revive)
    cli/command/container/run.go:176:3: redefines-builtin-id: redefinition of the built-in function close (revive)
            close, err := attachContainer(ctx, dockerCli, &errCh, config, createResponse.ID)
            ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit f663c981676580ffb199fe5431c9628c46c7095e)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>